### ISSUE TITLE
Service Worker

### ISSUE THREAD

**Issue by alex-saunders** [FormidableLabs/runpkg#116]
Runpkg is pretty quick at fetching package/file contents but is fairly slow at dependency fetching. We could look into the possibility of introducing a service worker to cache dependency requests to speed up return visits. The SW could purely cache the dependency file names/locations and maybe the file size, leaving the request for the file contents as a normal, uncached request.

**Comment by kiraarghy** [comment]
I had a play around with this on Friday I had a couple of issues with it intercepting non unpkg url fetch requests. I set it up for a `Stale while revalidate` cache strategy so that we would return from cache then fetch the latest info and push that to the cache.

I'll continue to have a play with it but isn't a 'high priority' rn.

**Comment by lukejacksonn** [comment]
This has been done as part of https://github.com/FormidableLabs/runpkg/pull/139
