### ISSUE TITLE
Keep path info when searching for files

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/runpkg#162]
Quick feature suggestion I think would be useful.

When searching for a file in tree view, it would be useful to still have the tree/path information of each file.

## Current filtering result
![Screenshot 2019-11-28 at 15 19 54](https://user-images.githubusercontent.com/10779424/69817836-5dffed00-11f3-11ea-8ec9-7b853ce359c2.png)

## Desired filtering result
![Screenshot 2019-11-28 at 15 24 49](https://user-images.githubusercontent.com/10779424/69817855-6a844580-11f3-11ea-9e92-3578c575bfd4.png)

**Comment by alex-saunders** [comment]
Hey @andyrichardson , removing the tree view was a conscious design decision to make the search feel more like a regular 'fuzzy' style search. However, I can see your point and a search returning 2 files with the same name (but in different locations) leads to a confusing result. What do think about keeping the flat structure but showing the full file path, so that it can be determined how the results are different?

**Comment by lukejacksonn** [comment]
This was fixed earlier today by @alex-saunders https://github.com/FormidableLabs/runpkg/pull/168. Thanks for the report @andyrichardson 🙇
