### ISSUE TITLE
Add asynchronous searching for files

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/runpkg#191]
## About

It would be cool if searching for files in a package was done asynchronously!

This would prevent changes to the search input from being blocked while searching is taking place.

![92566523eb658031783196dd3ac58028](https://user-images.githubusercontent.com/10779424/107029535-1259b380-67a7-11eb-9668-ffada7b3f164.gif)

**Comment by robwalkerco** [comment]
After some investigation, the filtering itself is not causing this performance issue.
The cause is the quantity of search results rendered, especially after only entering the initial search character. 

For example, when searching @sanity/base for `index`, after entering the `i` character there are 2016 matching files. This causes the `PackageOverview` component to take 104ms to render.
After entering `in` there are 470 file matches, rendering in 24 ms.
After entering `ind` there are 286 file matches, rendering in 21 ms.
After entering `inde` there are 201 file matches, rendering in 17 ms.

It's the 104ms render that is causing the text input lag as shown in the original issue details.

A more suitable resolution for this issue would be limiting the number of results rendered using pagination, ideally with windowed infinite scrolling, so that the current scrolling behaviour can be maintained.

**Comment by robwalkerco** [comment]
Thanks for flagging this issue @andyrichardson ❤️
